name: build

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and extract
        run: |
          docker buildx create --use
          docker buildx build --load --platform linux/${{ matrix.arch }} -t zz-build:${{ matrix.arch }} .
          docker create --name temp-container zz-build:${{ matrix.arch }}
          docker cp temp-container:/build/jpeg-archive/jpeg-recompress jpeg-recompress-${{ matrix.arch }}
          docker rm temp-container
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release
        run: |
          gh release delete v2.2.0 --yes || true
          gh release create v2.2.0 --title "v2.2.0"
          gh release upload v2.2.0 ./jpeg-recompress-amd64 ./jpeg-recompress-arm64 --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  