name: build

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and extract
        run: |
          mkdir -p build
          docker buildx create --use
          docker buildx build --load --platform linux/${{ matrix.arch }} -t zz-build:${{ matrix.arch }} .
          docker create --name temp-container zz-build:${{ matrix.arch }}
          docker cp temp-container:/build/jpeg-archive/jpeg-recompress build/jpeg-recompress-${{ matrix.arch }}
          docker rm temp-container
      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: zz-build-jpeg-recompress
        with:
          path: build
          key: build
  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: build
          key: build
      - name: Release
        run: |
          gh release create v2.2.0 --title "v2.2.0" || true
          gh release upload v2.2.0 ./build/jpeg-recompress-amd64 --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  