name: build

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build, extract and release
        run: |
          docker buildx create --use
          docker buildx build --platform linux/${{ matrix.arch }} -t zz-build .
          docker create --name temp-container zz-build
          docker cp temp-container:/build/jpeg-archive/jpeg-recompress jpeg-recompress
          docker rm temp-container
          gh release delete "2.2.0-${{ matrix.arch }}" --yes || true
          gh release create "2.2.0-${{ matrix.arch }}" jpeg-recompress --title "2.2.0-${{ matrix.arch }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
