name: build

on:
  workflow_dispatch:

jobs:
  build:
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and extract
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker buildx create --use
          docker buildx build --load --platform linux/${{ matrix.arch }} \
            -t ghcr.io/${{ github.repository_owner }}/zz-build-jpeg-recompress:2.2.0 \
            --push .
          mkdir -p build-${{ matrix.arch }}
          docker create --name temp-container zz-build-jpeg-recompress:2.2.0
          docker cp temp-container:/build/jpeg-archive/jpeg-recompress \
            build-${{ matrix.arch }}/jpeg-recompress-${{ matrix.arch }}
          docker rm temp-container
      - name: Cache
        uses: actions/cache/save@v4
        with:
          path: build-${{ matrix.arch }}
          key: build-${{ matrix.arch }}
  release:
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: build-amd64
          key: build-amd64
      - name: Restore cache
        uses: actions/cache/restore@v4
        with:
          path: build-arm64
          key: build-arm64
      - name: Release
        run: |
          gh release create v2.2.0 --title "v2.2.0" || true
          gh release upload v2.2.0 ./build-amd64/jpeg-recompress-amd64 ./build-arm64/jpeg-recompress-arm64 --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  