name: release

on:
  workflow_dispatch:

jobs:
  release:
    permissions: write-all
    if: github.ref_name == github.event.repository.default_branch
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Extract and release
        run: |
          docker pull --platform linux/amd64 ghcr.io/iamasc8277/zz-build-jpeg-recompress:2.2.0
          docker create --platform linux/amd64 --name extract-container-amd64 ghcr.io/iamasc8277/zz-build-jpeg-recompress:2.2.0
          docker cp extract-container-amd64:/build/jpeg-archive/jpeg-recompress jpeg-recompress-amd64
          docker rm extract-container-amd64
          docker pull --platform linux/arm64 ghcr.io/iamasc8277/zz-build-jpeg-recompress:2.2.0
          docker create --platform linux/arm64 --name extract-container-arm64 ghcr.io/iamasc8277/zz-build-jpeg-recompress:2.2.0
          docker cp extract-container-arm64:/build/jpeg-archive/jpeg-recompress jpeg-recompress-arm64
          docker rm extract-container-arm64
          gh release delete v2.2.0 -y || true
          gh release create v2.2.0 --title "v2.2.0"
          gh release upload v2.2.0 jpeg-recompress-amd64 jpeg-recompress-arm64 --clobber
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

